# Uncomment this line to define a global platform for your project
platform :ios, '8.4'

target 'TouristHelper' do
 pod 'TouristHelperCore', :path => '../TouristHelperCore'
 pod 'PureLayout'
end

target 'TouristHelperTests' do

end